# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 63ec20278ac825d6547108b1e3a5d088f9df88995643ccf21a6720f878d006cb1a78611e62080b7cc1c6a36cf34ad1714446b5c482a9edd6002e67c25d69afe2

test:
  secret_key_base: c20e80a6d750375d67c8fe5e3cd9117ae83142af306bbccdab87138e51b0b402a510c98cb61354d25e8942ec56f8a11fdf5727fd5c63f11159e43392ff137b59

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
